### ISSUE TITLE
Weird width behavior

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-table#1]
After recent changes the `juicy-tile-table` starts to act weird with width property.

One image should describe the issue better than tons of words.

![juicy-tile-table](https://cloud.githubusercontent.com/assets/6435556/12744529/137132c6-c995-11e5-81db-caf39958f7f5.gif)

**Comment by tomalec** [comment]
Thanks for reporting. It seems that `calc` in `<col>` width is a problem: http://jsbin.com/xenewubuqi/edit?html,css,output

**Comment by tomalec** [comment]
`calc` in `<col>` fails to render http://jsbin.com/juqafi/1/edit?html,css,output
- in Chrome when mixing units, for multiple columns,
- in IE & FF when `%` used 
  
  https://bugzilla.mozilla.org/show_bug.cgi?id=957915:
  
  > I would be very disinclined to do this unless there is an actual specification for the behavior...

**Comment by tomalec** [comment]
Ok seems we need to revert our `calc` tweaks.

W3C [CSS3 Values spec](https://www.w3.org/TR/css3-values/#calc-computed-value):

> Given the complexities of width and height calculations on table cells and table elements, math expressions involving percentages for widths and heights on table columns, table column groups, table rows, table row groups, and table cells in both auto and fixed layout tables MAY be treated as if auto had been specified.

**Comment by tomalec** [comment]
I have posted a question on that in W3C repo:
w3c/csswg-drafts/issues/94
