### ISSUE TITLE
Invalid tile width behavior

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-table#3]
Similar to #2 the tile width is also calculated wrong.

The image below shows that the `<td>` has greater width compare to the actual tile, which has a static non-flexible value.

![image](https://cloud.githubusercontent.com/assets/6435556/13047876/7171e260-d3e2-11e5-8182-df38b279ae04.png)

Ways to reproduce:
1. Open [simple example page](http://juicy.github.io/juicy-tile-editor/examples/juicy-tile-table/simple.html). 
2. Select the image.
3. Press calculate width button or input manual value of `304px`.
4. Investigate the shadow `<td>` and `<div>` sizes.

**Comment by tomalec** [comment]
This is due to the padding assigned by external CSS https://github.com/Juicy/juicy-tile-editor/blob/gh-pages/examples/juicy-tile-table/simple.html#L52
So the HTML based size of this tile is `2px + 300px + 2px`, thefore `304px` is correctly calculated size.

**Comment by tomalec** [comment]
So you can either treat it as correct result, or change tha padding in the editor if you don't want such padding.

**Comment by miyconst** [comment]
@tomalec you are wrong.
1. The tile size is `367px` not `304px`.
2. The style `juicy-tile-table > *` does not effect `<td>` inside Shadow DOM.

Am I missing something?

**Comment by miyconst** [comment]
Another screenshot for same issue:

![image](https://cloud.githubusercontent.com/assets/6435556/13057726/54da1550-d41e-11e5-95ef-260091191c31.png)

As you can see from the screenshot, the `<td>` does not have any padding, and it's size is `472px`, while the `<div>` inside same as setup object has fixed size of `304px`.

**Comment by tomalec** [comment]
The `<td>` is wider, as it is in the grid, so again that is desired behavior.
According to the [building algorithm](https://github.com/Juicy/juicy-tile-grid/blob/gh-pages/algorithm.md) as column contains fixed and flexbile size tiles, it should be flexible (As this is table not grid layout, flexible means it's relative to the parent (grid/table) not to the free space left)

So, `<td>` size is different, but `juicy-tile` size is fixed as it should.

`div.juicy-tile` is a tile, so the element, that you should highlight, and check dimensions, not `<td>` or any other  (`<tr>,<col>,<table>`) Shadow DOM element. With upcoming features like virtual labels, I'll pollute Shadow DOM with even more elements and weird nesting, but `.juicy-tile` will always be a selector for a tile.

Is it now clear enough? If not feel free to call me on HO.

**Comment by miyconst** [comment]
Well.. looks like I have to put all rows into a separate group if I want to have a fully non-flexible column.

I would still prefer to highlight the entire `<td>`, otherwise there will be a non-selectable gap, which would confuse people even more.

**Comment by tomalec** [comment]
I think it could be clickable & selectable, but will be non-highlight-able ;) Or we could select it with dashed line or something. BTW gutters are also non-selectable, and I think it's good as well.
