### ISSUE TITLE
Tiles should hide overflow content

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-table#4]
Right now shadow `<div>` tile adds scroll bar if the content inside goes out of the bounds. I think this is a wrong behaviour.

![image](https://cloud.githubusercontent.com/assets/6435556/13048097/dd09d6b2-d3e3-11e5-83ee-2b7902901f01.png)

**Comment by tomalec** [comment]
Long time ago we agreed with @Starcounter-Jack and @warpech that this is the only way user and component may survive with bad design.

Do we want to change that?

**Comment by miyconst** [comment]
I am not sure whether we want to change that, but this is not how it works in `juicy-tile-grid`, and that is why I get used to `overflow: hidden;` in tiles.

**Comment by tomalec** [comment]
Then I'd say it's bug in grid. @warpech do you agree?

**Comment by warpech** [comment]
Technically: what is actually causing the scrollbar to appear? I have created a codepen http://codepen.io/warpech/pen/dGEJGe?editors=1111, which shows that box shadow:
- is not counted in `getBoundingClientRect().height`
- does not trigger a scrollbar with `overflow: scroll`/`overflow: auto`

@tomalec, can you reproduce the problem in a codepen?

---

Technical possibilities aside, there are 3 possible solutions to solve such problem:
1. the excessive content bleeds out of the grid cell (like `overflow: visible`)
2. the excessive content is cut off (like `overflow: hidden`)
3. the excessive content triggers a scrollbar (like `overflow: scroll`/`overflow: auto`)

For every point above I can give an example when it would be desired. This is what makes it hard to choose one. 

If we need to have one, then I vote for keeping 3. In the long term I would actually propose to add a dropdown to choose.

**Comment by tomalec** [comment]
@warpech, I thinm OP is about shadow DOM `<div>`, not `<div>` with `box-shadow` ;)

---

If point 2 is desired, app dev may wrap element within a `div`. I think 1. is not desired in regards of mixing. As we would like to avoid cases when app A widget overlays/blocks app B UI.

We thought that tile should be a element's space, like page/iframe, If your element does not fit in iframe, you can either add scroll bars, or stretch iframe ("grow with content"), the content cannot bleed out of your window. Responsive app/element should rather adapt to given space.

**Comment by warpech** [comment]
I think that point (2) would actually never be desired, because it will only mask problems instead of fixing them. And it can be achieved by wrapping, as @tomalec suggests.

Points 1 and 3 would be desired, but how could we know which one to apply? If the only thing that bleeds out is a shadow, I would like (1) to apply. If content bleeds out, then I would like (3) to apply.

**Comment by tomalec** [comment]
I'm glad we agree on 2.

> Points 1 and 3 would be desired, but how could we know which one to apply? If the only thing that bleeds out is a shadow, I would like (1) to apply. If content bleeds out, then I would like (3) to apply.

Like this http://codepen.io/anon/pen/BKdovg?editors=1101 ?

I would assume, that both overflow, and visible could be desired by the designer in some cases.

I think the way to go is also "do not fight with browser" and "expose more CSS-like features in the editor". We already have 3x3 control, which decides whether the element should be stretched to the cell size (stands for `height: 100%;` in tile's CSS), or put in to left corner. Also we have control to say: "Stretch the track (row/column) if my element will grow"
Why can't we introduce overflow control, to be able to say: "If my content is bigger that the space I gave: a) add scrollbar, b) let the content overflow, c) hide the content"?

If we would like not to introduce featuritis we can keep the behavior as in codepen.

**Comment by miyconst** [comment]
As @tomalec said, in different places designers would like to have different behavior, that is why I like the idea to introduce the new feature in the editor.

The new feature requires some more work and time, before that we may/should stick with the behavior of the codepen.

**Comment by warpech** [comment]
I am against featuritis of course. For me, the codepen demonstrates exactly what we need. So, how is it different from what we already have in `j-t-t`?

**Comment by tomalec** [comment]
>  how is it different from what we already have in j-t-t?

in `j-t-t` we simply need to remove `overflow:auto;` from `div.juicy-tile` (`.fixed` in codepen)

**Comment by tomalec** [comment]
Codepen behavior implemented. Now element itself (shadow, outline, etc.) may overflow, but it's content cannot - it's handled by `overflow:auto`. This overflow behavior of content can be controlled by regular CSS style (inline/stylesheet) of an element.

If we would like to have a editor/setup feature to change it, we can create another issue.
