### ISSUE TITLE
How to deal with inline-block tiles

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-table#5]
When an `inline-block` element is a tile, then a white space added before the element which looks like a padding.

![image](https://cloud.githubusercontent.com/assets/6435556/13048190/839e2668-d3e4-11e5-806c-7dc44d47382e.png)

And this is how it looks with `display: block;`.

![image](https://cloud.githubusercontent.com/assets/6435556/13048202/9b6fef74-d3e4-11e5-8a39-058707479a60.png)

The `display: inline-block;` adds a non-removable padding and the element does not fit in a tile with exact same height as the element is. We should solve it somehow,  though I am not sure how. 

cc @warpech, @tomalec

**Comment by miyconst** [comment]
ping

**Comment by warpech** [comment]
Where does the padding come from? Is it a CSS quirk or j-t-t issue?

**Comment by miyconst** [comment]
The padding comes from browser.

This is how browser distribute `inline` and `block` elements inside `<content>`: https://jsfiddle.net/r0sndqvj/

![image](https://cloud.githubusercontent.com/assets/6435556/13469838/48eaf11e-e0a9-11e5-8b17-a5558e2b9099.png)

**Comment by tomalec** [comment]
It is not the `<content>` that makes it block, it's the div: https://jsfiddle.net/fLnut2cd/

**Comment by miyconst** [comment]
How is your example differs from mine?

The yellow padding on top of the `<input>` and at the bottom of `<span>` is still there.

![image](https://cloud.githubusercontent.com/assets/6435556/13474705/8972bdd2-e0bf-11e5-8629-0a811d31405f.png)

**Comment by tomalec** [comment]
"Yellow: Shadow DOM **div** container. "
the yellow background around the input comes from the fact, than input is shorter than line height.

**Comment by miyconst** [comment]
Yes, it's the `<div>`, but what it changes? The `<div>` does not have any css padding, and there is no white space between `<div>` and `<content>`.

The `juicy-tile-table` tile structure is:

``` html
<td>
    <div><content></content></div>
</td>
```

That is why I repeated it.

**Comment by tomalec** [comment]
This is not the padding. It's line height difference, as in just:

``` html
<div class="outter">
  <div class="inner">
    AA
  </div>
  <input class="inner">
  <span class="inner">span</span>

</div>
```

https://jsfiddle.net/dhzn1fxf/

**Comment by miyconst** [comment]
Okay, I am not saying it's a padding.

What I am saying is that there is an extra space between the tile and content inside the tile with `display: inline;` and `display: inline-block;` elements.

This leads to a frustrating behavior.
- User selects a tile.
- User presses calculate height button.
- Editor calculates the height.
- Editor set's the tile's height.
- Tile appears with scroll for extra space before/after content in the tile.

And I don't know how to deal with it. So, my question is not what is that, and how to call it, but how should we deal with it in the editor.

**Comment by tomalec** [comment]
Without deep investigation I suspect that  this is caused by bad css on the tile itself, or a bad way in which calculator calculates the tile size.

**Comment by miyconst** [comment]
> I suspect that this is caused by bad css on the tile itself

I was not able to eliminate the space by applying css to tile's `<td>`, `<div>`, or `<content>`. Applying `display: block;` to the element inside the tile solves the issue.

> or a bad way in which calculator calculates the tile size

Even if calculator would be able to calculate the height including the white space, the user would still left frustrated. Calculate means the tile should be exact same size as element inside, but the tile gets bigger size.

**Comment by tomalec** [comment]
I would postpone this issue, after juicy/juicy-composer will be used, as it will take care of all shadow dom magic, and `juicy-tile-*` will only apply some css (and table structure) on top of it

**Comment by miyconst** [comment]
This issue has gone with css fixes for shadows from @tomalec.
