### ISSUE TITLE
Gutter causes uneven align of the elements

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-tile-table#6]
I am running Launcher + People. I have noticed that elements in a virtual group are misaligned, especially when gutter is > 0.

The problematic parts of my layout:
- FirstName label - width 2/12, height 32px (grow with content)
- FirstName input - width 10/12, height 37px (gwc)
- LastName label - width 2/12, height 32px (gwc)
- LastName input - width 10/12, height 37px (gwc)

There are two problems:
1. LastName label and input are slightly misaligned when gutter == 0
2. LastName label and input are greatly misaligned when gutter > 0

I can see in Chrome DevTools that when gutter == 0, there are 4 TR elements. When gutter > 0, there are 6 TR elements. There might me something wrong with rowspan, etc.

See the screengrab:

![bug](https://cloud.githubusercontent.com/assets/566463/13111352/a11a02f0-d585-11e5-9047-db90a8ad875c.gif)

This is my source for the virtual group:

``` json
{"id":"root","direction":"horizontal","gutter":15,"items":[{"gutter":0,"items":[{"width":"25%","widthFlexible":true,"priority":0.5,"id":"People/0","height":84,"itemName":"Person details","hidden":false,"uid":"root1-People/02-root3-root_34-People/05"},{"gutter":15,"items":[{"width":130,"widthFlexible":false,"priority":1,"id":"People/13","height":29,"itemName":"Add phone number","hidden":false,"precalculateWidth":true,"uid":"root1-People/02-root3-root_34-root_06-People/137"},{"width":126,"widthFlexible":false,"priority":0.8225600779460933,"id":"People/10","height":29,"itemName":"Add email address","hidden":false,"precalculateWidth":false,"uid":"root1-People/02-root3-root_34-root_06-People/108"},{"width":92,"widthFlexible":false,"priority":0.6451201558921866,"id":"People/7","height":29,"itemName":"Add address","hidden":false,"precalculateWidth":true,"uid":"root1-People/02-root3-root_34-root_06-People/79"}],"id":"root_0","priority":0.484375,"width":"75%","height":29,"hidden":false,"itemName":"Group 1","rightToLeft":true,"tightGroup":true,"widthFlexible":true,"uid":"root1-People/02-root3-root_34-root_06","precalculateWidth":false,"precalculateHeight":false}],"id":"root_3","priority":0.734375,"width":"100%","height":84,"hidden":false,"itemName":"Group 4","widthFlexible":true,"uid":"root1-People/02-root3-root_34"},{"gutter":12,"items":[{"width":"16.666666666666668%","widthFlexible":true,"priority":0.46875,"id":"People/1","height":32,"itemName":"First name:","hidden":false,"uid":"root1-People/02-root3-root_110-People/111","heightDynamic":true},{"width":"83.33333333333333%","widthFlexible":true,"priority":0.439453125,"id":"People/2","height":37,"itemName":"<div>","hidden":false,"uid":"root1-People/02-root3-root_110-People/212","heightDynamic":true},{"width":"16.666666666666668%","widthFlexible":true,"priority":0.4119873046875,"id":"People/3","height":32,"itemName":"Last name:","hidden":false,"uid":"root1-People/02-root3-root_110-People/313","heightDynamic":true},{"width":"83.33333333333333%","widthFlexible":true,"priority":0.38623809814453125,"id":"People/4","height":37,"itemName":"<div>","hidden":false,"uid":"root1-People/02-root3-root_110-People/414","heightDynamic":true}],"id":"root_1","priority":0.548236608505249,"width":"100%","height":138,"hidden":false,"itemName":"Group 2","tightGroup":true,"widthFlexible":true,"heightFlexible":false,"heightDynamic":false,"precalculateHeight":true,"uid":"root1-People/02-root3-root_110"},{"width":"100%","widthFlexible":true,"priority":0.36209821701049805,"id":"People/5","height":30,"itemName":"Addresses:","hidden":false,"heightDynamic":true,"uid":"root1-People/02-root3-People/515"},{"width":"100%","widthFlexible":true,"priority":0.3394670784473419,"id":"People/6","height":74,"itemName":"This person does not Ã¢â‚¬Â¦","hidden":false,"heightDynamic":true,"uid":"root1-People/02-root3-People/616"},{"width":"100%","widthFlexible":true,"priority":0.2983597369166091,"id":"People/8","height":30,"itemName":"Emails:","hidden":false,"heightDynamic":true,"uid":"root1-People/02-root3-People/829"},{"width":"100%","widthFlexible":true,"priority":0.27971225335932104,"id":"People/9","height":37,"itemName":"This person does not Ã¢â‚¬Â¦","hidden":false,"heightDynamic":true,"uid":"root1-People/02-root3-People/930"},{"width":"100%","widthFlexible":true,"priority":0.24584084767909076,"id":"People/11","heightDynamic":true,"height":1,"itemName":"Phones:","hidden":false,"uid":"root1-People/02-root3-People/1139"},{"width":"100%","widthFlexible":true,"priority":0.23047579469914758,"id":"People/12","height":25,"itemName":"This person does not Ã¢â‚¬Â¦","hidden":false,"heightDynamic":true,"uid":"root1-People/02-root3-People/1240"},{"gutter":15,"items":[{"width":60,"widthFlexible":false,"priority":0.20256661643479767,"id":"People/14","height":36,"itemName":"Save","hidden":false,"precalculateWidth":true,"uid":"root1-People/02-root3-root_249-People/1450"},{"width":75,"widthFlexible":false,"priority":0.18990620290762283,"id":"People/15","height":36,"itemName":"Cancel","hidden":false,"precalculateWidth":false,"uid":"root1-People/02-root3-root_249-People/1551"}],"id":"root_2","priority":0.20256661643479767,"width":"100%","height":36,"hidden":false,"itemName":"Group 3","tightGroup":true,"widthFlexible":true,"uid":"root1-People/02-root3-root_249","precalculateWidth":false},{"width":"100%","widthFlexible":true,"priority":0.17873524979540972,"id":"People/16","heightDynamic":true,"height":1,"itemName":"Delete Cancel","hidden":false,"uid":"root1-People/02-root3-People/1652","precalculateHeight":false},{"height":0,"heightDynamic":true,"precalculateHeight":true,"width":"100%","widthFlexible":true,"priority":0.169328131385125,"id":"People/17","itemName":"<dom-bind-notifier>","uid":"root1-People/02-root3-People/1753","hidden":true},{"height":0,"heightDynamic":true,"precalculateHeight":true,"width":"100%","widthFlexible":true,"priority":0.16041612447011844,"id":"People/18","itemName":"<dom-bind-notifier>","uid":"root1-People/02-root3-People/1854","hidden":true}],"width":1000,"itemName":"PersonPage.html","precalculateHeight":true,"uid":"root1-People/02-root3"}
```

@tomalec can you take a look?

**Comment by tomalec** [comment]
That's not the gutter that aligns elements uneven, that's you ;)

> FirstName label - width 2/12, height **32px** (grow with content)
> FirstName input - width 10/12, height **37px** (gwc)
> LastName label - width 2/12, height **32px** (gwc)
> LastName input - width 10/12, height **37px** (gwc)

`32 != 37` 

You can fix it my making elements even. For example `height: 37px`.

But with your setup:

> when gutter == 0, there are 4 TR elements. When gutter > 0, there are 6 TR elements

If `gutter = 0`, with your heights, rows should look like follows:
1. from `0` to `32px` - the end of first tile
2. from `32px` to `37px` - the end of second tile
3. from `37px` to `64px = (32+32)px` - the end of third tile
4. from `64px` to `74px = (37+37)px` - the end of last tile

gutters add even more rows.

Everything goes as described at https://github.com/Juicy/juicy-tile-table/blob/gh-pages/algorithm.md

Please note, that we are building grid out of (4) elements, **NOT** placing (non-spanning) elements into (2x2) grid. As there is not arbitrary grid given.

---

If we will imperatively say for example: "Let there be 12 column grid!", entire story would look completely different.

---

Yet, another approach on building layouts, would be to create grid with non spanning elements, but this comes to discussion at https://github.com/Juicy/juicy-tile-list/issues/49

**Comment by warpech** [comment]
So you mean that `juicy-tile-grid` behaved the same way? I haven't noticed that but I guess you are right.

@Starcounter-Jack has came up with a proposal how to fix this. We could use a "snap to guideline" feature. This is known from Adobe Illustrator, etc. It means that guidelines cannot be closer than X pixels to each other. In our case, this could be 10px, etc. If two guidelines are closer than X, then the bigger one replaces the smaller one.

**Comment by tomalec** [comment]
It works in grid same way.

I'm afraid "snap to guideline" needs a HO or live meeting. .

Are you aware that such feature will break items dimensions? Plus it will need some exceptions, to make sure that snapping will not remove the grid area for a tile, nor push two tiles to the same area..

Please remember, that we are building grid out of elements, and we do not have any number of grid-lines given from the beginning.

Moreover, especially row lines (in height) may be highly dependent of content, and change continuously. `em` size may look better here, but we do not know `em` value of tile content, plus it may be different in different tiles.

---

If we would like to switch the thing we build, and the relation between given sizes to the outcome.

I get and idea:
- Dimensions given by app dev, are either 
  - fixed (images, icons) - will be obeyed precisely
  - flexible & relative - could be rounded (see below)
- Each layoutable area `<juicy-tile-grid>`/`<starcounter-include>`, gets arbitrary fixed number of columns. This number could be set relatively to container size like in media/element-queries , e.g. 2 for small container, 4 for medium, 8 for big, 12 for huge.
- Designer may change the number of columns, as he/she wants to per each partial/`juicy-tile-grid`

Then:
- if element is fixed,
  - and fits in a cell, it's placed ther alone,
  - and does not fit, it spans,
- if element is flexible, like 30%, it spans number of tracks closest to given fraction

Thanks to that, 
- we will always have nice, easy to understand and manage, more -Gestalt-compliant grid,
- granularity/precision could be increased, by increasing the number of columns,
- developer hints, are more like hints, not exact setup,
- designer setup is more precise, and grid-aware,

But, 
- I still cannot find buch benefits for height.
