### ISSUE TITLE
per-item setup should extend not overwrite `defaultTileSetup`

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-tile-table#7]
Currently `defaultTileSetup` provided in `juicy-tile-*` attribute is used if and only if there is no setup given in JSON. See https://github.com/Juicy/juicy-tile-list/blob/gh-pages/README.md#space_invader-construction-per-item-declarative-setup-experimental-feature
We have 4 setups that may be used, currently they overwrite each other.

Example:

``` html
<juicy-tile-table>
    <div>A0</div>
</juicy-tile-table>
<juicy-tile-table  
    defaultTileSetup='{
        "height": 1,
        "heightDynamic": true,
        "width": "100%",
        "widthFlexible": true
    }' 
    setup='{
        "width": 900,
        "items":[{
             "id": "2"
             "width": "20%",
             "height": 200,
             "priority": 0.9
        }]
    }'>
    <div>B0</div>
    <div juicy-style="width: 100px; height: 10px;">B1</div>
    <div juicy-style="width: 200px; height: 20px; heightDynamic: 1;">B2</div>
</juicy-tile-table>
```
- `A0` setup uses some hard-coded `juicy-tile-table` defaults.
- `B0`: `{
      "height": 1,
      "heightDynamic": true,
      "width": "100%",
      "widthFlexible": true
  }` as given in `defaultTileSetup` overwrites hard-coded `juicy-tile-table` defaults.
- `B1`: `{width: 100px; height: 10px;}` given in attribute (layout hint) overwrites other defaults
- `B2`: `{
           "id": "2"
           "width": "20%",
           "height": 200,
           "priority": 0.9
      }` given in specific layout overwrites all others

The questions are:
1. Should we change overwrite to extend? 
2. If so, should we do it for all steps/ways? Or just for `defaultTileSetup` -> `juicy-style`

@miyconst , @warpech  WDYT?

I'm asking mainly because I noticed that Konstantin used it in extend way in his first tests. I think it may look convenient from CSS-like perspective.

On the other hand from JSON perspective (and we provide hard-coded default, `defualtTileSetup` and `setup` in JSON format) it's not that obvious. Moreover it may hit performance as we would need to extend 4 times `n` nested objects on every pageload. Plus it may be harder to maintain from code perspective.

I suspect it would be easier to implement, and would perform waaay more efficient when we will finally switch to setup leaned more to CSS Grid spec, and CSS end format. Then, it would just be browser's **Cascading**StyleSheet

**Comment by miyconst** [comment]
I think that **extend** should work only between `B0` and `B1` layers to compose JSON setup value.

Once the JSON (`B2`) value saved, it should overwrite all previous values.

**Comment by tomalec** [comment]
Ok, then the cost of extending would reduce to just cloning `defaulttileSetup` as extend could be incorporated into CSS parsing without any cost.

The only doubt I have i that the way to provide layout setup is already complicated as we have 4 different ways to do so. Adding some exceptions, and rules between those will complicate it even more.
If it's fine for you all, and you think app devs would get it, I'm fine.

**Comment by tomalec** [comment]
Please note that app developer may not be guaranteed of any `defaultTileSetup` that he/she will extend, as `defaultTileSetup` is given by a Launcher. On the other hand he/she may not like to specify everything so strictly as it's just a hint.

**Comment by warpech** [comment]
The concept of **layout hinting** means that the value of `juicy-style` is just a **hint** for `j-t-t`. 

So it should enhance the `j-t-t`'s understanding of the tile, not overwrite the style. It is `j-t-t`'s role (or something that extends it) to do an interpretation of that hint.

So my vote goes for "extend". And sometimes not even extend but "consider extending".

Also, `defaulttilesetup` is not even something that might exist. I can imagine that instead of this:

```
<juicy-tile-table defaulttilesetup='{ "height": 98, "width": 80}' gutter="10" refreshonmutation name="/Launcher/launchpad" setup='[[cloneJSON(layout)]]'>
```

I would have this:

```
<launcher-launchpad-icons refreshonmutation name="/Launcher/launchpad" setup='[[cloneJSON(layout)]]'>
```

**Comment by tomalec** [comment]
Ok, so we will go for extending.

Just to note `<launcher-launchpad-icons refreshonmutation name="/Launcher/launchpad" setup='[[cloneJSON(layout)]]'>` also have `defaultTileSetup`, as this attribute also has a default written in code.
